# These are supported funding model platforms

github: [darpanaswal]        # GitHub Sponsors
# ko_fi: darpanaswal  # Ko-fi (uncomment if you set one up)
# open_collective:             # Open Collective
